[package]
name = "modbus"
version = "0.0.3"
authors = ["Falco Hirschenberger <falco.hirschenberger@gmail.com>"]
repository = "https://github.com/hirschenberger/modbus-rs.git"
homepage = "https://github.com/hirschenberger/modbus-rs.git"
documentation = "https://hirschenberger.github.io/modbus-rs"
license = "MIT"
readme = "README.md"
description = "Pure Rust modbus implementation"
keywords = ["modbus", "hardware"]

[dependencies]
enum_primitive = "0.1.0"
num = "0.1.27"
rustc-serialize = "0.3.16"
bincode = "0.4.0"
byteorder = "0.4.2"
clippy = {version = "*", optional = true}

[dev-dependencies]
lazy_static = "0.1.15"

[features]
default=[]
