[package]
name = "modbus"
version = "0.0.1"
authors = ["Falco Hirschenberger <hirschen@itwm.fhg.de>"]
repository = "https://github.com/hirschenberger/modbus.git"
homepage = "https://github.com/hirschenberger/modbus.git"
documentation = "https://hirschenberger.github.io/modbus"
license = "MIT"
readme = "README.md"
description = "Pure Rust modbus implementation"
keywords = ["modbus", "hardware"]

[dependencies]
enum_primitive = "0.1.0"
num = "0.1.27"
rustc-serialize = "0.3.16"
bincode = "0.4.0"
byteorder = "0.4.2"
